import acl from "@/data/festivals/acl-2026.json";
import coachella from "@/data/festivals/coachella-2026.json";
import lollapalooza from "@/data/festivals/lollapalooza-2026.json";
import outsideLands from "@/data/festivals/outside-lands-2026.json";
import primavera from "@/data/festivals/primavera-2026.json";
import { cacheGet, cacheSet } from "./cache";
import { FESTIVAL_REGISTRY, fetchFestivalLineup } from "./festival-wiki";

/* Festival store (roadmap §0.1). Two layers:
   - SEEDS: repo JSON snapshots (generated by scripts/festival-refresh.mjs,
     or hand-curated when Wikipedia lacks the lineup — e.g. Outside Lands).
   - Redis override (`v2:festivals:all`): written by the weekly cron
     (/api/cron/refresh-festivals), so lineups stay fresh between deploys.
   Readers merge: Redis wins per slug, seeds fill the gaps. */

export interface FestivalAct {
  name: string;
  tier?: string; // "headliner" | undefined
  day?: string;
}

export interface Festival {
  slug: string;
  name: string;
  year: number;
  dates: string;
  /** ISO last day — festivals past this date drop off the featured list */
  endsOn?: string;
  location: string;
  source?: string;
  lineup: FestivalAct[];
}

const SEEDS: Festival[] = [
  lollapalooza as Festival,
  coachella as Festival,
  outsideLands as Festival,
  primavera as Festival,
  acl as Festival,
];

const STORE_KEY = "v2:festivals:all";
const STORE_TTL_S = 60 * 24 * 60 * 60; // 60d safety net; cron rewrites weekly

async function allFestivals(): Promise<Festival[]> {
  const fresh = (await cacheGet<Festival[]>(STORE_KEY)) ?? [];
  const bySlug = new Map(fresh.map((f) => [f.slug, f]));
  // seed order is the display order; Redis provides freshness, not ordering
  const merged = SEEDS.map((seed) => bySlug.get(seed.slug) ?? seed);
  for (const f of fresh) if (!SEEDS.some((s) => s.slug === f.slug)) merged.push(f);
  return merged;
}

/** Featured list: upcoming festivals only — past editions drop off. */
export async function getFestivals(): Promise<Festival[]> {
  const today = new Date().toISOString().slice(0, 10);
  return (await allFestivals()).filter((f) => !f.endsOn || f.endsOn >= today);
}

/** Direct links to past editions keep working — only the listing filters. */
export async function getFestival(slug: string): Promise<Festival | undefined> {
  return (await allFestivals()).find((festival) => festival.slug === slug);
}

/** Weekly cron body: re-parse every registry festival from Wikipedia and
 *  store the batch in Redis. Failures keep the previous data (seed or last
 *  good refresh) — a missing section must never blank a live festival. */
export async function refreshFestivalsFromWiki(): Promise<
  Array<{ slug: string; result: string }>
> {
  const previous = new Map(
    (((await cacheGet<Festival[]>(STORE_KEY)) ?? []) as Festival[]).map((f) => [f.slug, f])
  );
  const summary: Array<{ slug: string; result: string }> = [];
  const batch: Festival[] = [];

  for (const entry of FESTIVAL_REGISTRY) {
    try {
      const { acts, source } = await fetchFestivalLineup(entry);
      batch.push({
        slug: entry.slug,
        name: entry.name,
        year: entry.year,
        dates: entry.dates,
        endsOn: entry.endsOn,
        location: entry.location,
        source: `${source} (${new Date().toISOString().slice(0, 10)})`,
        lineup: acts,
      });
      summary.push({ slug: entry.slug, result: `ok: ${acts.length} acts` });
    } catch (err) {
      const kept = previous.get(entry.slug);
      if (kept) batch.push(kept);
      summary.push({
        slug: entry.slug,
        result: `failed (${err instanceof Error ? err.message : "?"}) — kept ${
          kept ? "previous refresh" : "seed"
        }`,
      });
    }
    await new Promise((r) => setTimeout(r, 500));
  }

  await cacheSet(STORE_KEY, batch, STORE_TTL_S);
  return summary;
}

/* ── directory festivals: lazy lineups + interest tracking ─────────
   The MusicBrainz directory (festival-directory.ts) lists ~1,265 festivals;
   we do NOT crawl lineups for them up front. The first visit to a directory
   festival triggers Wikipedia discovery, and the result (or a "no lineup
   found" marker) is stored. Interest counters decide what the weekly cron
   re-refreshes — nobody searching = no calls spent. */

import { cacheHashGetAll, cacheHashIncr } from "./cache";
import { getDirectoryEntry } from "./festival-directory";
import { baseFestivalName, discoverFestivalLineup } from "./festival-wiki";

const DISC_KEY = (mbid: string) => `v2:festival:disc:${mbid}`;
const NO_LINEUP_KEY = (mbid: string) => `v2:festival:nolineup:${mbid}`;
const DISC_TTL_S = 60 * 24 * 60 * 60; // refreshed by interest-driven cron
const NO_LINEUP_TTL_S = 7 * 24 * 60 * 60; // retry weekly — lineups get announced
const INTEREST_KEY = "v2:fest:interest";
const DIRECTORY_YEAR = 2026;

export const directorySlug = (mbid: string) => `mb-${mbid}`;

/** Count a search-click / page-open toward the refresh priority list. */
export function recordFestivalInterest(slugOrId: string): void {
  void cacheHashIncr(INTEREST_KEY, slugOrId);
}

const entryYear = (entry: { name: string; begin: string | null }): number => {
  const fromName = entry.name.match(/(19|20)\d\d/)?.[0];
  if (fromName) return Number(fromName);
  if (entry.begin) return Number(entry.begin.slice(0, 4));
  return DIRECTORY_YEAR;
};

const formatDates = (begin: string | null, end: string | null) =>
  begin ? (end && end !== begin ? `${begin} → ${end}` : begin) : "dates TBA";

/** Directory festival by mbid: stored lineup, or discover-on-first-visit.
 *  Returns a Festival with an empty lineup when Wikipedia has nothing yet. */
export async function getDirectoryFestival(mbid: string): Promise<Festival | undefined> {
  const stored = await cacheGet<Festival>(DISC_KEY(mbid));
  if (stored) return stored;

  const entry = await getDirectoryEntry(mbid);
  if (!entry) return undefined;

  const year = entryYear(entry);
  const shell: Festival = {
    slug: directorySlug(mbid),
    name: baseFestivalName(entry.name),
    year,
    dates: formatDates(entry.begin, entry.end),
    location: "",
    lineup: [],
  };

  if (await cacheGet<boolean>(NO_LINEUP_KEY(mbid))) return shell;

  const found = await discoverFestivalLineup(entry.name, year).catch(() => null);
  if (!found) {
    await cacheSet(NO_LINEUP_KEY(mbid), true, NO_LINEUP_TTL_S);
    return shell;
  }
  const festival: Festival = {
    ...shell,
    source: `${found.source} (${new Date().toISOString().slice(0, 10)})`,
    lineup: found.acts,
  };
  await cacheSet(DISC_KEY(mbid), festival, DISC_TTL_S);
  return festival;
}

/** Cron: re-discover the most-clicked directory festivals (and retry ones
 *  whose lineup wasn't announced yet), highest interest first. */
export async function refreshInterestedFestivals(
  limit: number,
  deadlineMs: number
): Promise<Array<{ slug: string; result: string }>> {
  const interest = await cacheHashGetAll(INTEREST_KEY);
  const wanted = Object.entries(interest)
    .filter(([key]) => key.startsWith("mb-"))
    .sort((a, b) => b[1] - a[1])
    .slice(0, limit)
    .map(([key]) => key.slice(3));

  const summary: Array<{ slug: string; result: string }> = [];
  for (const mbid of wanted) {
    if (Date.now() > deadlineMs) {
      summary.push({ slug: "…", result: "stopped: cron time budget reached" });
      break;
    }
    const entry = await getDirectoryEntry(mbid);
    if (!entry) continue;
    const year = entryYear(entry);
    const found = await discoverFestivalLineup(entry.name, year).catch(() => null);
    if (found) {
      const festival: Festival = {
        slug: directorySlug(mbid),
        name: baseFestivalName(entry.name),
        year,
        dates: formatDates(entry.begin, entry.end),
        location: "",
        source: `${found.source} (${new Date().toISOString().slice(0, 10)})`,
        lineup: found.acts,
      };
      await cacheSet(DISC_KEY(mbid), festival, DISC_TTL_S);
      summary.push({ slug: entry.name, result: `ok: ${found.acts.length} acts` });
    } else {
      await cacheSet(NO_LINEUP_KEY(mbid), true, NO_LINEUP_TTL_S);
      summary.push({ slug: entry.name, result: "no lineup on wikipedia yet" });
    }
    await new Promise((r) => setTimeout(r, 400));
  }
  return summary;
}
